apiVersion: experimental.kontinue.io/v1
kind: Workload
metadata:
  name: spring-hello-world
  labels:
    app.kubernetes.io/name: spring-hello-world
    app.tanzu.vmware.com/workload-type: web
spec:
  git:
    # update when code is pushed to a new location
    url: https://github.com/hnandiwada/spring-hello-world-educates.git
    ref:
      branch: main
  env:
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

